/**
 * CarEntry.js — Read-only model for the report-service.
 * WHY DUPLICATED HERE: In this microservice setup the car-entry table is OWNED
 *   and written by the car-entry/parking services. The report-service keeps its
 *   own matching model definition (a "read copy") purely so it can run Sequelize
 *   queries against the same shared table — it never inserts/updates rows here.
 *   The field shapes must mirror the owner's schema or queries would fail.
 */
const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/db');

/**
 * Read-model for the shared 'car_entries' table.
 * Table is owned/created by the parking-service; we only read it here.
 */
const CarEntry = sequelize.define(
  'CarEntry',
  {
    id: {
      type: DataTypes.UUID, // UUID primary key, generated by the owning service
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    plateNumber: {
      type: DataTypes.STRING, // car's licence plate
      allowNull: false,
    },
    parkingCode: {
      type: DataTypes.STRING, // which lot the car used (links to Parking.code)
      allowNull: false,
    },
    entryDateTime: {
      type: DataTypes.DATE, // when the car arrived — filtered for "incoming" reports
      allowNull: false,
    },
    exitDateTime: {
      type: DataTypes.DATE, // when it left — null while still parked; used for "outgoing"
      allowNull: true,
    },
    chargedAmount: {
      type: DataTypes.DECIMAL(10, 2), // fee billed on exit — summed for revenue reports
      allowNull: true,
    },
    durationMinutes: {
      type: DataTypes.INTEGER, // parking duration; null until the car exits
      allowNull: true,
    },
    status: {
      type: DataTypes.ENUM('parked', 'exited'), // 'parked' = still in, 'exited' = gone
      allowNull: false,
      defaultValue: 'parked',
    },
  },
  {
    tableName: 'car_entries', // bind to the exact existing table name (no pluralisation guess)
    timestamps: true, // owner stores createdAt/updatedAt; we just read them
  }
);

module.exports = CarEntry;
